function fileLog = importfileLog(filename, dimension)
%IMPORTFILE2 Import data from a text file
%  ITER500DIM2START3RANK0 = IMPORTFILE2(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  ITER500DIM2START3RANK0 = IMPORTFILE2(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  iter500dim2start3rank0 = importfile2("/Users/hendrik_w/MAThe/InC/output/iter500_dim2_start3_rank0.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Jul-2020 13:42:35

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [1, Inf];
nColsInfo = 7;
%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2*dimension+nColsInfo);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableTypes = repmat(["double"],1,2*dimension+nColsInfo);
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
fileLog = readtable(filename, opts);

%% Convert to output type
fileLog = table2array(fileLog);
end