function fileTimes = importfileTimes(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  fileTimes = IMPORTFILE2(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the numeric data.
%
%  fileTimes = IMPORTFILE2(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  fileTimes = importfile2("/Users/hendrik_w/MAThe/InC/output/iter1000_dim20_start0_prop40_swap0_rank0_times.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jul-2020 13:04:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
fileTimes = readtable(filename, opts);

%% Convert to output type
fileTimes = table2array(fileTimes);
end